global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ZaraLive Application - Node.js
  - job_name: 'zaralive-app'
    static_configs:
      - targets: ['host.docker.internal:3001']  # Your Node.js app
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # ZaraLive Frontend - React
  - job_name: 'zaralive-frontend'
    static_configs:
      - targets: ['host.docker.internal:3000']  # Your React app
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']
    metrics_path: '/metrics'

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'

  # Node Exporter (if you want system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
